name: Build and publish docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push container image to registries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: ["22.04", "20.04"]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set artifact names
        run: |
          env
          if [[ "${{ matrix.ubuntu_version }}" == "22.04" ]]; then
              echo UBUNTU_NODOT="2204" >> $GITHUB_ENV
              echo CONTAINER_FLAVOR="latest=true" >> $GITHUB_ENV
          else
              echo UBUNTU_NODOT="2004" >> $GITHUB_ENV
              echo CONTAINER_FLAVOR="" >> $GITHUB_ENV
          fi

      - name: Extract metadata (tags, labels) for Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ env.UBUNTU_NODOT }}.{{date 'YYYYMMDD'}}
          flavor: ${{ env.CONTAINER_FLAVOR }}

      - name: test
        run: |
          echo "${{ steps.meta.outputs.labels }}"
          echo "${{ steps.meta.outputs.tags }}"

#      - name: Build and push docker image
#        uses: docker/build-push-action@v3
#        with:
#          build-args: |
#            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
#          context: .
#          platforms: linux/amd64,linux/arm64,linux/arm/v7
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
