name: Build and publish docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push container image to registries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: ["22.04", "20.04"]
        image_suffix: ["", "-dev", "-ansible-dev"]
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set artifact names and targets
      run: |
        env
        if [[ "${{ matrix.ubuntu_version }}" == "22.04" ]]; then
            echo TAG_PREFIX="" >> $GITHUB_ENV
            echo CONTAINER_FLAVOR="latest=true" >> $GITHUB_ENV
        else
            echo TAG_PREFIX="2004." >> $GITHUB_ENV
            echo CONTAINER_FLAVOR="" >> $GITHUB_ENV
        fi

        if [[ "${{ matrix.image_suffix }}" == *"-dev" ]]; then
            echo "IMAGE_TARGETS=linux/amd64,linux/arm64" >> $GITHUB_ENV
        else
            echo "IMAGE_TARGETS=linux/amd64,linux/arm64,linux/arm/v7" >> $GITHUB_ENV
        fi

    - name: Extract metadata (tags, labels) for Docker image
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ github.repository }}${{ matrix.image_suffix }}
          ghcr.io/${{ github.repository }}${{ matrix.image_suffix }}
        tags: |
          type=raw,value=${{ env.TAG_PREFIX }}{{date 'YYYYMMDD'}}
        flavor: ${{ env.CONTAINER_FLAVOR }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
        target: base${{ matrix.image_suffix }}
        build-args: |
          UBUNTU_VERSION=${{ matrix.ubuntu_version }}
        context: .
        platforms: ${{ env.IMAGE_TARGETS }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
